import React from "react"
// import { Link } from "gatsby"
import { Global,  css } from '@emotion/core';

import Layout from "../components/Layout"
import SEO from "../components/SEO"
import HeaderImage from '../components/HeaderImage'

const IndexPage = () => (
  <Layout>
    <Global styles={css`font-family: sans-serif;`} />
    <SEO title="Home" />
    <HeaderImage />
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
    <h2>I'm some content on a page.</h2>
    <h3>I'm some content on a page!</h3>
  </Layout>
)

export default IndexPage
